# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
builds:
- binary: tinywww
  env:
  - CGO_ENABLED=0
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
release:
  name_template: "{{ .ProjectName }}-{{ .Version }}"
  github:
    owner: embano1
    name: tinywww
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
dockers:
  - dockerfile: Dockerfile.goreleaser
    image_templates:
    - "embano1/tinywww:latest"
    - "embano1/tinywww:{{ .Tag }}"
    build_flag_templates:
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.authors=mgasch@vmware.com"