# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
builds:
- binary: tinywww
  env:
  - CGO_ENABLED=0
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
release:
  name_template: "{{ .ProjectName }}-{{ .Version }}"
  github:
    owner: embano1
    name: tinywww
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
dockers:
  - dockerfile: Dockerfile.goreleaser
    image_templates:
    - "embano1/tinywww:latest"
    - "embano1/tinywww:{{ .Tag }}"