# ubuntu:bionic-20200921 linux/amd64
FROM ubuntu@sha256:45c6f8f1b2fe15adaa72305616d69a6cd641169bc8b16886756919e7c01fa48b

RUN apt-get update && apt-get install -y \
    ca-certificates=20190110~18.04.1 \
    && rm -rf /var/lib/apt/lists/*

COPY tinywww /usr/local/bin

USER nobody:nogroup
ENTRYPOINT ["/usr/local/bin/tinywww"]
